<a href="https://colab.research.google.com/github/Delta9529/Tinder_millennial_match/blob/main/Tinder_dphi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Loading the dataset!!

In [6]:
import pandas as pd
import numpy as np

In [7]:
dataset = pd.read_csv("https://raw.githubusercontent.com/dphi-official/Datasets/master/Tinder_Millennial_Match/train_set_label.csv")

In [8]:
dataset.head(5)

,ID,Segment type,Segment Description,Answer,Count,Percentage,It became a relationship
0,292890.8970,web,"Meridian, Idaho",No,0.000000,0.000000,0
1,292887.9870,web,"Meridian, Idaho",No,0.000000,0.000000,0
2,292894.0656,gender,"Meridian, Idaho",No,499.173606,0.225255,0
3,292887.1180,web,"Meridian, Idaho",No,0.000000,0.000000,0
4,292893.6561,gender,"Meridian, Idaho",No,455.925963,0.211360,0

Cleaning & EDA

In [9]:
dataset.describe()
dataset.isnull().sum()

ID                          0
Segment type                0
Segment Description         0
Answer                      0
Count                       0
Percentage                  0
It became a relationship    0
dtype: int64

In [10]:
dataset_n = dataset.drop(["ID","Segment Description"],axis=1)
dataset_n.head()

  Segment type Answer       Count  Percentage  It became a relationship
0          web     No    0.000000    0.000000                         0
1          web     No    0.000000    0.000000                         0
2       gender     No  499.173606    0.225255                         0
3          web     No    0.000000    0.000000                         0
4       gender     No  455.925963    0.211360                         0

In [11]:
x = dataset_n.drop("It became a relationship",axis=1)
x.head()

  Segment type Answer       Count  Percentage
0          web     No    0.000000    0.000000
1          web     No    0.000000    0.000000
2       gender     No  499.173606    0.225255
3          web     No    0.000000    0.000000
4       gender     No  455.925963    0.211360

In [12]:
y = pd.DataFrame(dataset_n.iloc[:,-1].values)
y.head()

   0
0  0
1  0
2  0
3  0
4  0

Encoding

In [13]:
 from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
x['Answer']= label_encoder.fit_transform(x['Answer']) 
print(x.head())

  Segment type  Answer       Count  Percentage
0          web       1    0.000000    0.000000
1          web       1    0.000000    0.000000
2       gender       1  499.173606    0.225255
3          web       1    0.000000    0.000000
4       gender       1  455.925963    0.211360

In [14]:
x.head(5)

  Segment type  Answer       Count  Percentage
0          web       1    0.000000    0.000000
1          web       1    0.000000    0.000000
2       gender       1  499.173606    0.225255
3          web       1    0.000000    0.000000
4       gender       1  455.925963    0.211360

In [15]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
x_en = pd.DataFrame(ohe.fit_transform(x[["Segment type"]]).toarray())
x_new=pd.concat([x,x_en],axis=1)
x_new

     Segment type  Answer        Count  Percentage    0    1    2    3
0             web       1     0.000000    0.000000  0.0  0.0  0.0  1.0
1             web       1     0.000000    0.000000  0.0  0.0  0.0  1.0
2          gender       1   499.173606    0.225255  1.0  0.0  0.0  0.0
3             web       1     0.000000    0.000000  0.0  0.0  0.0  1.0
4          gender       1   455.925963    0.211360  1.0  0.0  0.0  0.0
...           ...     ...          ...         ...  ...  ...  ...  ...
1891          web       1     0.000000    0.000000  0.0  0.0  0.0  1.0
1892       mobile       1  1203.190399    0.312360  0.0  1.0  0.0  0.0
1893       gender       1   806.378820    0.488025  1.0  0.0  0.0  0.0
1894       gender       1  1149.529381    0.488984  1.0  0.0  0.0  0.0
1895          web       1     0.000000    0.000000  0.0  0.0  0.0  1.0

[1896 rows x 8 columns]

In [16]:
x_new = x_new.drop("Segment type",axis = 1)

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_new, y, test_size = 0.2, random_state = 0)

In [18]:
x_train.shape

(1516, 7)

In [19]:
x_test.shape

(380, 7)

In [20]:
y_train.head()

      0
31    1
789   1
461   1
621   1
1226  0

Fitting Logistic Regression Model

In [21]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

LogisticRegression(random_state=0)

Predicting on Splitted Data

In [22]:
prediction = classifier.predict(x_test)
prediction

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,

array([0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0])

In [23]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, prediction)
cm

array([[225,  26],
       [ 43,  86]])

In [24]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test, prediction)
acc

0.8184210526315789

Loading and predicting Test dataset !!

In [25]:
test_data = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/Tinder_Millennial_Match/test_set_label.csv')

In [26]:
test_data.head()

,ID,Segment type,Segment Description,Answer,Count,Percentage
0,292974.2311,university,"University of California, Davis",Yes,0.230742,0.115371
1,292889.7996,web,"Meridian, Idaho",No,0.000000,0.000000
2,293724.0350,university,"Westport, CT",Yes,0.000000,0.000000
3,292884.0724,mobile,"Meridian, Idaho",No,1497.699982,0.388752
4,292882.0964,mobile,"Meridian, Idaho",No,1439.464988,0.373646

In [27]:
test_data.isnull().sum()

ID                     0
Segment type           0
Segment Description    0
Answer                 0
Count                  0
Percentage             0
dtype: int64

In [28]:
test_data = test_data.drop(["ID","Segment Description"],axis=1)
test_data.head()

  Segment type Answer        Count  Percentage
0   university    Yes     0.230742    0.115371
1          web     No     0.000000    0.000000
2   university    Yes     0.000000    0.000000
3       mobile     No  1497.699982    0.388752
4       mobile     No  1439.464988    0.373646

In [29]:
 from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder() 
test_data['Answer']= label_encoder.fit_transform(test_data['Answer']) 
print(test_data.head())

  Segment type  Answer        Count  Percentage
0   university       2     0.230742    0.115371
1          web       1     0.000000    0.000000
2   university       2     0.000000    0.000000
3       mobile       1  1497.699982    0.388752
4       mobile       1  1439.464988    0.373646

In [30]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
t_d = pd.DataFrame(ohe.fit_transform(x[["Segment type"]]).toarray())
testdata_new=pd.concat([x,t_d],axis=1)
testdata_new

     Segment type  Answer        Count  Percentage    0    1    2    3
0             web       1     0.000000    0.000000  0.0  0.0  0.0  1.0
1             web       1     0.000000    0.000000  0.0  0.0  0.0  1.0
2          gender       1   499.173606    0.225255  1.0  0.0  0.0  0.0
3             web       1     0.000000    0.000000  0.0  0.0  0.0  1.0
4          gender       1   455.925963    0.211360  1.0  0.0  0.0  0.0
...           ...     ...          ...         ...  ...  ...  ...  ...
1891          web       1     0.000000    0.000000  0.0  0.0  0.0  1.0
1892       mobile       1  1203.190399    0.312360  0.0  1.0  0.0  0.0
1893       gender       1   806.378820    0.488025  1.0  0.0  0.0  0.0
1894       gender       1  1149.529381    0.488984  1.0  0.0  0.0  0.0
1895          web       1     0.000000    0.000000  0.0  0.0  0.0  1.0

[1896 rows x 8 columns]

In [31]:
test = testdata_new.drop("Segment type",axis=1)

In [32]:
prediction_new = classifier.predict(test)
prediction_new.shape

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,

(1896,)

In [33]:
res = pd.DataFrame(prediction_new)
res.head()

   0
0  0
1  0
2  0
3  0
4  0

In [34]:
res.columns = ["prediction"]

In [ ]:
# from google.colab import files
# res.to_csv('tinder.csv')
# files.download('tinder.csv')